/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LeaveRequest {
  'month' : bigint,
  'staffId' : string,
  'preferredDutyDates' : Array<bigint>,
  'year' : bigint,
  'noDutyDates' : Array<bigint>,
  'leaveDates' : Array<bigint>,
}
export interface Roster {
  'month' : bigint,
  'year' : bigint,
  'entries' : Array<RosterEntry>,
}
export interface RosterEntry {
  'day' : bigint,
  'flags' : Array<string>,
  'pgId' : string,
  'thirdLayerId' : string,
  'manualOverride' : boolean,
  'secondLayerId' : string,
}
export interface Staff {
  'id' : string,
  'active' : boolean,
  'name' : string,
  'role' : string,
}
export interface StatutoryHoliday {
  'day' : bigint,
  'month' : bigint,
  'year' : bigint,
}
export interface UserProfile { 'staffId' : [] | [string], 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addHoliday' : ActorMethod<[StatutoryHoliday], undefined>,
  'addStaff' : ActorMethod<[Staff], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteStaff' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaveRequest' : ActorMethod<
    [string, bigint, bigint],
    [] | [LeaveRequest]
  >,
  'getMonthStats' : ActorMethod<[bigint, bigint], Array<[string, bigint]>>,
  'getRoster' : ActorMethod<[bigint, bigint], [] | [Roster]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listHolidays' : ActorMethod<[bigint, bigint], Array<StatutoryHoliday>>,
  'listLeaveRequestsForMonth' : ActorMethod<
    [bigint, bigint],
    Array<LeaveRequest>
  >,
  'listStaff' : ActorMethod<[], Array<Staff>>,
  'removeHoliday' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveRoster' : ActorMethod<[bigint, bigint, Array<RosterEntry>], undefined>,
  'updateStaff' : ActorMethod<[Staff], undefined>,
  'upsertLeaveRequest' : ActorMethod<[LeaveRequest], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];