/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const StatutoryHoliday = IDL.Record({
  'day' : IDL.Nat,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
});
export const Staff = IDL.Record({
  'id' : IDL.Text,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'staffId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const LeaveRequest = IDL.Record({
  'month' : IDL.Nat,
  'staffId' : IDL.Text,
  'preferredDutyDates' : IDL.Vec(IDL.Nat),
  'year' : IDL.Nat,
  'noDutyDates' : IDL.Vec(IDL.Nat),
  'leaveDates' : IDL.Vec(IDL.Nat),
});
export const RosterEntry = IDL.Record({
  'day' : IDL.Nat,
  'flags' : IDL.Vec(IDL.Text),
  'pgId' : IDL.Text,
  'thirdLayerId' : IDL.Text,
  'manualOverride' : IDL.Bool,
  'secondLayerId' : IDL.Text,
});
export const Roster = IDL.Record({
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'entries' : IDL.Vec(RosterEntry),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHoliday' : IDL.Func([StatutoryHoliday], [], []),
  'addStaff' : IDL.Func([Staff], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteStaff' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaveRequest' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Opt(LeaveRequest)],
      ['query'],
    ),
  'getMonthStats' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getRoster' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Roster)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listHolidays' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(StatutoryHoliday)],
      ['query'],
    ),
  'listLeaveRequestsForMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(LeaveRequest)],
      ['query'],
    ),
  'listStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
  'removeHoliday' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveRoster' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Vec(RosterEntry)], [], []),
  'updateStaff' : IDL.Func([Staff], [], []),
  'upsertLeaveRequest' : IDL.Func([LeaveRequest], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const StatutoryHoliday = IDL.Record({
    'day' : IDL.Nat,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
  });
  const Staff = IDL.Record({
    'id' : IDL.Text,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'staffId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const LeaveRequest = IDL.Record({
    'month' : IDL.Nat,
    'staffId' : IDL.Text,
    'preferredDutyDates' : IDL.Vec(IDL.Nat),
    'year' : IDL.Nat,
    'noDutyDates' : IDL.Vec(IDL.Nat),
    'leaveDates' : IDL.Vec(IDL.Nat),
  });
  const RosterEntry = IDL.Record({
    'day' : IDL.Nat,
    'flags' : IDL.Vec(IDL.Text),
    'pgId' : IDL.Text,
    'thirdLayerId' : IDL.Text,
    'manualOverride' : IDL.Bool,
    'secondLayerId' : IDL.Text,
  });
  const Roster = IDL.Record({
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'entries' : IDL.Vec(RosterEntry),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHoliday' : IDL.Func([StatutoryHoliday], [], []),
    'addStaff' : IDL.Func([Staff], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteStaff' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaveRequest' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Opt(LeaveRequest)],
        ['query'],
      ),
    'getMonthStats' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getRoster' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Roster)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listHolidays' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(StatutoryHoliday)],
        ['query'],
      ),
    'listLeaveRequestsForMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(LeaveRequest)],
        ['query'],
      ),
    'listStaff' : IDL.Func([], [IDL.Vec(Staff)], ['query']),
    'removeHoliday' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveRoster' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Vec(RosterEntry)], [], []),
    'updateStaff' : IDL.Func([Staff], [], []),
    'upsertLeaveRequest' : IDL.Func([LeaveRequest], [], []),
  });
};

export const init = ({ IDL }) => { return []; };